### ISSUE TITLE
Doesn't work as intendent on Linux, missing some settings and features

### ISSUE THREAD

**Issue by Jeremi360** [MakovWait/godots#20] opened 2023-09-22 09:25 UTC
So after I download godot and try to install it the Choose Dir is broken.
As path on top is empty and I can't choose any place in folder that it opens.

Also for me this is wrong that by default it downloads and installs Godots into `user://`
As this make it hard to find this godots to for example connect to Godot-tools in VSCode.
So there should be settings that allow to setup download and default install dir.
Also it would be good if it would have `Scan` opitons for Projects and Godot Versions.

**Comment by MakovWait** [comment] 2023-09-22 13:45
Please, try [this](https://github.com/MakovWait/godots/releases/tag/v1.1.rc1) version. Seems like all the things you mentioned should be fixed there. 

And if the Choose Dir bug is not fixed in v.1.1rc1, let me know, will investigate it further.

**Comment by Jeremi360** [comment] 2023-09-22 14:34
@MakovWait Just tried 1.1rc1 version and it works like a dream, except for few things:
1. some setting for example download dir don't apply until I restart app
2. When app opens File/Dir Dialog it has this strange rectangle drawn in it:
![image](https://github.com/MakovWait/godots/assets/1294815/39bc1819-07a2-48c2-8106-31531d5b0cb3)
3. When I try to use import I can't change godot version - I try to choose 3.2.3 but it keep getting back to 3.5.2
![image](https://github.com/MakovWait/godots/assets/1294815/3911aa51-afab-4ae0-a186-89a2bcbfc7a7)

**Comment by MakovWait** [comment] 2023-09-22 14:51
Oh thanks! I'll fix all the bugs excepting the second one - I have no idea why it acts like this :c 
I've seen this bug in Godot editor itself one time, so I think the problem is in the core maybe. 

Thank you again!

**Comment by Jeremi360** [comment] 2023-09-23 07:28
@MakovWait I was happy to help :smile:

**Closed** 2023-09-23 07:56 UTC
